version: '3.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: aaaaa
      MYSQL_DATABASE: benis
      MYSQL_USER: benisuser
      MYSQL_PASSWORD: benispassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  photoview:
    build:
      context: ../PhotoView
      dockerfile: Dockerfile
      target: dev
    volumes: 
      - ../PhotoView/src:/app/src
    ports:
      - 8888:8888
    
  workerview:
    build:
      context: ../WorkerView
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ../WorkerView/src:/app/src
    ports:
      - 8889:8888

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  #caddy:
  #  image: caddy:2-alpine
  #  volumes:
  #    - ./Caddyfile:/etc/caddy/Caddyfile
  #    - ./certs:/etc/caddy/certs
  #  ports:
  #    - "80:80"
  #    - "443:443"