version: '3.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: immerscale1337
      MYSQL_DATABASE: db
      MYSQL_USER: lordimmerscaler
      MYSQL_PASSWORD: immerscale1337
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  photoview:
    build:
      context: ../PhotoView
      dockerfile: Dockerfile
      target: build
    volumes: 
      - ../PhotoView/src:/app/src
    ports:
      - 8888:8080
    
  workerview:
    build:
      context: ../WorkerView
      dockerfile: Dockerfile
      target: build
    volumes:
      - ../WorkerView/src:/app/src
    ports:
      - 8889:8080

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  reverseproxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy