version: '3.1'

services:
  db:
    image: immerscale.azurecr.io/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: immerscale1337
      MYSQL_DATABASE: db
      MYSQL_USER: lordimmerscaler
      MYSQL_PASSWORD: immerscale1337
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  photoview:
    image: immerscale.azurecr.io/docker-photoview:latest
    ports:
      - 8888:8080
    
  workerview:
    image: immerscale.azurecr.io/docker-workerview:latest
    ports:
      - 8889:8080

  backend:
    image: immerscale.azurecr.io/docker-backend:latest
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  reverseproxy:
    image: immerscale.azurecr.io/docker-reverseproxy:latest
    ports:
      - "80:80"
      - "443:433"
    depends_on:
      db:
        condition: service_healthy